config/routes.rb
FlickMultiperm::Application.routes.draw do
 devise_for :users, controllers: { sessions: "users/sessions", authentications: "authentications" } do
   get '/users/sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
   get '/sessions/new', to: 'index#index', as: :new_user_session
   get '/users/auth/:provider/callback', to: 'authentications#callback'
 end
 resources :user_sets
 resources :user_photos do
  collection do
    post 'hide'
    post 'remove'
    post 'restore'
    post 'publish'
  end
 end
 resources :authentications

  root 'user_sets#index'

  

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
end

app/models/flickr.rb
class Flickr
  PRIVACY_PUBLIC = 1
  PRIVACY_PRIVATE = 5
  API_PER_PAGE = 500

  attr_reader :obj
  def initialize current_user
    configs = Devise.omniauth_configs[:flickr].args

    FlickRaw.api_key = configs.first
    FlickRaw.shared_secret = configs.last

    flickr.access_token = current_user.authentications.first.access_token
    flickr.access_secret = current_user.authentications.first.access_secret
    @obj = flickr
  end

  def filter_sets_photos_query sets_photos, query = nil
    return sets_photos.select{|p| /#{query}/ =~ p.title } unless query.nil?
    sets_photos
  end

  def removed_photos set
    UserPhoto.where(user_set_id: set.id).where(is_include_set: false).order('updated_at ASC').all
  end

  def photos_with_modify_record  set, privacy, query
    counts = @obj.photosets.getInfo(photoset_id: set.id).count_photos
    photos = []
    (counts.to_f / self.class::API_PER_PAGE.to_f).ceil.times.each do |page|
      photos << @obj.photosets.getPhotos(photoset_id: set.id, privacy_filter: privacy, page: (page + 1)).photo
    end
    photos = photos.flatten
    user_photos = UserPhoto.where(id: photos.map{|p| p.id}).pluck(:id)

    ActiveRecord::Base.transaction do
      photos.each do |photo|
        unless user_photos.include? photo.id.to_i
          obj = UserPhoto.find_or_initialize_by(id: photo.id)
          obj.is_include_set = true
          obj.user_set = set
          obj.save!
        end
      end
    end
    self.filter_sets_photos_query photos, query
  end

  def remove_photo_by_set set, photo
      self.modify_photo_by_set set, photo, false
  end

  def restore_photo_by_set set, photo
      self.modify_photo_by_set set, photo, true
  end

  def modify_photo_by_set set, photo, is_include_set
    ActiveRecord::Base.transaction do
      if is_include_set
        @obj.photosets.addPhoto(photoset_id: set.id, photo_id: photo.id)
      else
        @obj.photosets.removePhoto(photoset_id: set.id, photo_id: photo.id)
      end
      obj = UserPhoto.find photo.id
      obj.is_include_set = is_include_set
      obj.save!
    end
  end

  def change_privacy photo, privacy
    is_public = 0
    is_family = 0
    is_friend = 0
    perm_comment = 3
    perm_addmeta = 2
    if self.class::PRIVACY_PUBLIC == privacy
      is_public = 1
    end
    @obj.photos.setPerms(photo_id: photo.id, is_public: is_public, is_family: is_family, is_friend: is_friend, perm_comment: perm_comment, perm_addmeta: perm_addmeta)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authentications
  devise :trackable, :omniauthable

  def set_for_flickr omniauth
    User.transaction do
      lock_obj = Authentication.find_by_provider_and_uid(omniauth['provider'], omniauth['uid'], lock: true)
      if lock_obj.nil?
        self.authentications.build self.get_flickr_args(omniauth)
      else
        lock_obj.update_attributes self.get_flickr_args(omniauth)
      end
      self.save!
    end
  end

  def get_flickr_args omniauth
    {
      uid: omniauth['uid'],
      provider: omniauth['provider'],
      name: omniauth['info']['name'],
      access_token: omniauth['credentials']['token'],
      access_secret: omniauth['credentials']['secret'],
    }
  end
end

app/models/user_photo.rb
class UserPhoto < ActiveRecord::Base
  belongs_to :user_set
end

app/models/user_set.rb
class UserSet < ActiveRecord::Base
  belongs_to :user, foreign_key: "user_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  def callback
    omniauth = request.env['omniauth.auth']
    @authentication = Authentication.find_by_provider_and_uid(omniauth['provider'], omniauth['uid'])
    if @authentication
      @user = @authentication.user
    else
      # New User
      @user = User.new
    end
    @user.set_for_flickr omniauth
    sign_in(:user, @user)
    redirect_to root_url
  end
end

app/controllers/user_photos_controller.rb
class UserPhotosController < ApplicationController
  
    before_filter do
  @set = UserSet.find self.photoset_by_photo_id(params[:user_photo][:id])
    @flick = Flickr.new @set.user
  end

  def publish
    @flick.change_privacy UserPhoto.find(params[:user_photo][:id]), Flickr::PRIVACY_PUBLIC
    redirect_to user_set_path(id: self.photoset_by_photo_id(params[:user_photo][:id]))
  end

  def hide
    @flick.change_privacy UserPhoto.find(params[:user_photo][:id]), Flickr::PRIVACY_PRIVATE
    redirect_to user_set_path(id: self.photoset_by_photo_id(params[:user_photo][:id]))
  end

  def remove
    @flick.remove_photo_by_set @set, UserPhoto.find(params[:user_photo][:id])
    redirect_to user_set_path(id: self.photoset_by_photo_id(params[:user_photo][:id]))
  end

  def restore
    @flick.restore_photo_by_set @set, UserPhoto.find(params[:user_photo][:id])
    redirect_to user_set_path(id: self.photoset_by_photo_id(params[:user_photo][:id]))
  end

  protected
  def photoset_by_photo_id id
    UserPhoto.where(id: id).pluck(:user_set_id).first
  end
end

app/controllers/user_sets_controller.rb
class UserSetsController < ApplicationController

  def index
    @user_sets = UserSet.all
  end

  def new
    flick = Flickr.new current_user
    @sets = flick.obj.photosets.getList.to_a
  end

  def create
    UserSet.create! user_set_params
  end

  def show
    set = UserSet.find params[:id]
    flick = Flickr.new set.user

    @q = params[:search][:q] if params[:search]
    @public_photos = flick.photos_with_modify_record set, Flickr::PRIVACY_PUBLIC, @q
    @private_photos = flick.photos_with_modify_record set, Flickr::PRIVACY_PRIVATE, @q
    @removed_photos = flick.removed_photos set
    
  end

  private
  def user_set_params
    param = params.require(:user_set).permit(:id, :title)
    param[:user] = current_user
    param
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authenticatons_helper.rb
module AuthenticatonsHelper
end

app/helpers/user_photos_helper.rb
module UserPhotosHelper
end

app/helpers/user_sets_helper.rb
module UserSetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FlickMultiperm</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<a href="/users/auth/flickr">sign in</a>
<a href="/user_sets/new">add my sets</a>
<%= yield %>

</body>
</html>

app/views/user_sets/index.erb
<% @user_sets.each do |set| %>
  <%= link_to "#{set.id} #{set.title}", set %><br />
<% end %>

app/views/user_sets/new.erb
<p>
<% @sets.each do |set| %>
  <%= "#{set.id} #{set.title} #{set.photos}" %><br />
  <%= form_for :user_set, url: user_sets_path  do |f| %>
    <%= f.hidden_field :id, value: set.id %>
    <%= f.hidden_field :title, value: set.title %>
    <%= f.submit 'Add' %>
  <% end %>
<% end %>
</p>

app/views/user_sets/show.erb
<h2> Public </h2>
<%= form_tag '', method: :get do |f| %>
  <%= text_field :search, :q, value: @q %>
  <%= submit_tag 'search' %>
<% end %>
<% @public_photos.each do |photo| %>
  <%= "#{photo.id} #{photo.title}" %><br />
  <%= form_for :user_photo, url: hide_user_photos_path  do |f| %>
    <%= f.hidden_field :id, value: photo.id %>
    <%= f.submit 'hide' %>
  <% end %>
<% end %>


<h2> Private </h2>

<% @private_photos.each do |photo| %>
  <%= "#{photo.id} #{photo.title}" %><br />
  <%= form_for :user_photo, url: remove_user_photos_path  do |f| %>
    <%= f.hidden_field :id, value: photo.id %>
    <%= f.submit 'Remove from set' %>
  <% end %>
  <%= form_for :user_photo, url: publish_user_photos_path  do |f| %>
    <%= f.hidden_field :id, value: photo.id %>
    <%= f.submit 'Publish to set' %>
  <% end %>
  <hr />
<% end %>

<h2>Removed</h2>
<% @removed_photos.each do |photo| %>
  <%= "#{photo.id} modify: #{photo.updated_at}" %><br />
  <%= form_for :user_photo, url: restore_user_photos_path  do |f| %>
    <%= f.hidden_field :id, value: photo.id %>
    <%= f.submit 'Restore to set' %>
  <% end %>
  <hr />
<% end %>